homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 5
  # metric for Metric, imperial for Imperial
  unit_system: metric
      
# Enables the frontend
frontend:

# Checks for available updates
# updater:

# Discover some devices automatically
# discovery:
 
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr

light:
  - platform: mqtt
    name: "Bathroom Lights"
    state_topic: "bathroom/lights/state"
    command_topic: "bathroom/lights/com"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Lounge Lights"
    state_topic: "lounge/lights/state"
    command_topic: "lounge/lights/com"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Hallway Light"
    state_topic: "hallway/lights/state"
    command_topic: "hallway/lights/com"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Kitchen Lights"
    state_topic: "kitchen/lights/state"
    command_topic: "kitchen/lights/com"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Dining Room Lights"
    state_topic: "dining/lights/state"
    command_topic: "dining/lights/com"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Front Room Lights"
    state_topic: "frontroom/lights/state"
    command_topic: "frontroom/lights/com"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Master Bedroom Lights"
    state_topic: "masterroom/lights/state"
    command_topic: "masterroom/lights/com"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Back Room Lights"
    state_topic: "backroom/lights/state"
    command_topic: "backroom/lights/com"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Frontyard Lights"
    state_topic: "frontyard/lights/state"
    command_topic: "frontyard/lights/com"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Backyard Lights"
    state_topic: "backyard/lights/state"
    command_topic: "backyard/lights/com"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Front Door Light"
    state_topic: "frontdoor/lights/state"
    command_topic: "frontdoor/lights/com"
    payload_on: "1"
    payload_off: "0"

switch:
  - platform: mqtt
    name: "Front Room Heating"
    state_topic: "frontroom/heating/state"
    command_topic: "frontroom/heating/com"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Master Room Heating"
    state_topic: "masterroom/heating/state"
    command_topic: "masterroom/heating/com"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Back Room Heating"
    state_topic: "backroom/heating/state"
    command_topic: "backroom/heating/com"
    payload_on: "1"
    payload_off: "0"

fan:
  - platform: mqtt
    name: "PIV System"
    state_topic: "piv/on/state"
    command_topic: "piv/on/com"
    speed_state_topic: "piv/speed/state"
    speed_command_topic: "piv/speed/set"
    payload_on: "1"
    payload_off: "0"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    speeds:
      - low
      - medium
      - high